USE car_sales;

-- Optional demo user
-- IMPORTANT: replace password_hash value with one generated by:
-- php -r "echo password_hash('demo123', PASSWORD_DEFAULT), PHP_EOL;"
INSERT INTO users (name, address, phone, email, username, password_hash)
VALUES (
  'Demo User',
  'Chaoyang Road 100',
  '13812345678',
  'demo@example.com',
  'demo001',
  '$2y$10$replace_with_real_hash_here................................'
)
ON DUPLICATE KEY UPDATE username = username;
